#!/usr/bin/env Rscript
# scripts/build_appendix_tables.R
# FOMA CER-COD-Paris | M7 session | governed by the M7 DEC
# Builds Online-Appendix Tables A.2-A.4 as Markdown fragments (build-artifact
# rule per DEC-054: no hand transcription; generated from committed run CSVs).
# R port of the withdrawn Python delivery (ERROR #49: unverified toolchain
# assumption); base R + stats only. Author-run via RStudio source() (Device
# Guard blocks direct Rscript.exe as of 2026-08-05; M7 DEC environment note).
# v2: TF_loo.csv real column names (cluster_id_dropped, cooks_d_cluster) +
# numeric-id label fallback via the note column.
#
# Sources (read-only, repo root):
#   output/T1_results.csv                  -> Table A.2 (A1 headline ref + A5 estimators)
#   output/TF_loo.csv (+ output/TF_influence.csv fallback for Cook's D)
#                                          -> Table A.3 (114 cluster LOO + influence)
#   output/T5_results.csv                  -> Table A.4 (D4 period FAT-PET-PEESE)
#
# Output: stdout + output/appendix_tables_A2_A4.md (UTF-8; the file is canonical --
#         Windows console rendering of the typographic minus may look garbled).
# Determinism: pure function of the input CSVs; no seeds needed.
# Failure mode: any violated pin stops with diagnostics (exit status 1) -- paste
# the full console output back into the session.

OUT_PATH <- file.path("output", "appendix_tables_A2_A4.md")
MINUS <- "\u2212"; EMDASH <- "\u2014"; ENDASH <- "\u2013"

# ---------- formatting (house style) ----------

m   <- function(s) gsub("-", MINUS, s, fixed = TRUE)
f3  <- function(x) m(sprintf("%.3f", x))
fmt_df <- function(df) {
  if (is.null(df) || is.na(df)) return(EMDASH)
  if (abs(df - round(df)) < 1e-9) sprintf("%d", as.integer(round(df)))
  else m(sprintf("%.1f", df))
}
fmt_p <- function(p) {
  if (is.null(p) || is.na(p)) return(EMDASH)
  if (p < 0.001) return("< .001")
  s <- if (p < 0.05) sprintf("%.4f", p) else sprintf("%.3f", p)
  sub("^0", "", s)
}
fmt_ci <- function(lb, ub) sprintf("[%s; %s]", f3(lb), f3(ub))
fmt_k  <- function(k) formatC(as.integer(k), format = "d", big.mark = ",")

# ---------- CSV access ----------

load_csv <- function(path, required = TRUE) {
  if (!file.exists(path)) {
    if (required) stop(sprintf("STOP: missing input %s (run from repo root).", path),
                       call. = FALSE)
    return(NULL)
  }
  df <- utils::read.csv(path, colClasses = "character", check.names = FALSE,
                        fileEncoding = "UTF-8-BOM")
  names(df) <- tolower(trimws(names(df)))
  if (nrow(df) == 0) stop(sprintf("STOP: empty CSV %s", path), call. = FALSE)
  df
}

numv <- function(row, ...) {
  for (nm in c(...)) {
    if (nm %in% names(row)) {
      v <- trimws(as.character(row[[nm]][1]))
      if (!(v %in% c("", "NA", "NaN", "None"))) {
        x <- suppressWarnings(as.numeric(v))
        if (!is.na(x)) return(x)
      }
    }
  }
  NA_real_
}

txtv <- function(row, ...) {
  for (nm in c(...)) {
    if (nm %in% names(row)) return(trimws(as.character(row[[nm]][1])))
  }
  NA_character_
}

pick <- function(df, crit) {
  keep <- rep(TRUE, nrow(df))
  for (nm in names(crit)) {
    col <- df[[nm]]
    if (is.null(col)) return(df[0, , drop = FALSE])
    keep <- keep & (trimws(as.character(col)) == crit[[nm]])
  }
  df[keep, , drop = FALSE]
}

one <- function(df, ctx, ...) {
  crit <- list(...)
  hit <- pick(df, crit)
  if (nrow(hit) != 1) {
    stop(sprintf("STOP [%s]: expected 1 row for {%s}, got %d. Header: %s",
                 ctx, paste(names(crit), unlist(crit), sep = "=", collapse = ", "),
                 nrow(hit), paste(sort(names(df)), collapse = ", ")), call. = FALSE)
  }
  hit
}

ci_of <- function(row, ctx) {
  lb <- numv(row, "ci_lb_z", "ci_lb", "ci_lower")
  ub <- numv(row, "ci_ub_z", "ci_ub", "ci_upper")
  if (!is.na(lb) && !is.na(ub)) return(c(lb, ub))
  est <- numv(row, "est_z", "est"); se <- numv(row, "se_z", "se")
  df  <- numv(row, "df")
  if (is.na(est) || is.na(se) || is.na(df)) {
    stop(sprintf("STOP [%s]: no CI columns and cannot derive (est/se/df missing). Header: %s",
                 ctx, paste(sort(names(row)), collapse = ", ")), call. = FALSE)
  }
  h <- stats::qt(0.975, df) * se
  c(est - h, est + h)
}

p_of <- function(row) {
  p <- numv(row, "p", "p_value", "pval")
  if (!is.na(p)) return(p)
  t <- numv(row, "t_stat", "t"); df <- numv(row, "df")
  if (is.na(t) || is.na(df)) return(NA_real_)
  2 * stats::pt(-abs(t), df)
}

pin <- function(cond, msg) if (!isTRUE(cond)) stop(paste("PIN FAIL:", msg), call. = FALSE)

# ---------- Table A.2 : alternative estimators ----------

build_a2 <- function(t1) {
  lines <- c(
    paste0("<!-- Table A.2 generated by scripts/build_appendix_tables.R from ",
           "output/T1_results.csv (A1::headline reference row; A5 alternative ",
           "estimators); PCC-r scale (Fisher-z rows transformed via tanh); ",
           "CIs shown only where CR2 Satterthwaite df >= 4 (TB-10 footnote) -->"),
    "| Estimator | k (ES) | Clusters | Estimate (r) | 95% CI | df |",
    "|---|---|---|---|---|---|")

  row_z_to_r <- function(r, label, ctx) {
    est_r <- tanh(numv(r, "est_z")); ci <- ci_of(r, ctx)
    list(line = sprintf("| %s | %s | %s | %s | %s | %s |", label,
                        fmt_k(numv(r, "k_es")), fmt_k(numv(r, "k_cluster")),
                        f3(est_r), fmt_ci(tanh(ci[1]), tanh(ci[2])),
                        fmt_df(numv(r, "df"))),
         est_str = sprintf("%s %s", f3(est_r), fmt_ci(tanh(ci[1]), tanh(ci[2]))))
  }
  row_r <- function(r, label, with_df = TRUE) {
    est <- numv(r, "est_z")  # PCC_r rows carry the estimate in the est column
    df  <- if (with_df) numv(r, "df") else NA_real_
    list(line = sprintf("| %s | %s | %s | %s | %s | %s |", label,
                        fmt_k(numv(r, "k_es")), fmt_k(numv(r, "k_cluster")),
                        f3(est), EMDASH, fmt_df(df)),
         df_str = fmt_df(df))
  }

  head <- one(t1, "A2/headline", analysis_id = "A1", spec = "headline")
  h <- row_z_to_r(head, paste0("Three-level CHE", ENDASH, "RVE (headline)"), "A2/headline")
  pin(h$est_str == m("-0.059 [-0.086; -0.031]"),
      sprintf("A2 headline: %s", h$est_str))
  lines <- c(lines, h$line)

  opc <- one(t1, "A2/opc", analysis_id = "A5", spec = "one_effect_per_cluster")
  lines <- c(lines, row_z_to_r(opc, paste0("One effect per cluster ", EMDASH,
             " RE (REML, Knapp", ENDASH, "Hartung)"), "A2/opc")$line)

  uw <- row_r(one(t1, "A2/uwls3", analysis_id = "A5", spec = "uwls3"), "UWLS+3")
  pin(uw$df_str == "2.3", sprintf("A2 UWLS+3 df: %s", uw$df_str))
  lines <- c(lines, uw$line)

  hs <- row_r(one(t1, "A2/hs", analysis_id = "A5", spec = "hs_es_level"),
              paste0("Hunter", ENDASH, "Schmidt (bare-bones)"), with_df = FALSE)
  lines <- c(lines, hs$line)

  wa <- row_r(one(t1, "A2/waap", analysis_id = "A5", spec = "waap_uwls"), "WAAP")
  pin(wa$df_str == "2.2", sprintf("A2 WAAP df: %s", wa$df_str))
  lines <- c(lines, wa$line)

  paste(lines, collapse = "\n")
}

# ---------- Table A.3 : LOO + influence ----------

build_a3 <- function(loo, infl) {
  label_c <- intersect(c("cluster_label", "study_label", "study", "cluster",
                         "label", "dropped_cluster", "cluster_dropped",
                         "cluster_id_dropped"),
                       names(loo))
  if (length(label_c) == 0) {
    stop(sprintf("STOP [A3]: no cluster label column in TF_loo.csv. Header: %s",
                 paste(sort(names(loo)), collapse = ", ")), call. = FALSE)
  }
  label_c <- label_c[1]
  labs_raw <- trimws(as.character(loo[[label_c]]))
  labs_ne <- labs_raw[labs_raw != ""]
  if (length(labs_ne) > 0 &&
      all(grepl("^-?[0-9]+(\\.[0-9]+)?$", labs_ne)) &&
      "note" %in% names(loo)) {
    label_c <- "note"  # numeric cluster ids: use the note column as display label
  }
  cooks_c <- intersect(c("cooks_d_cluster", "cooks_d", "cook_d", "cooks", "d"),
                       names(loo))

  cooks_map <- NULL
  if (length(cooks_c) == 0) {
    if (is.null(infl)) stop("STOP [A3]: Cook's D not in TF_loo.csv and TF_influence.csv missing.",
                            call. = FALSE)
    icl <- intersect(c(label_c, "cluster_label", "study_label", "cluster", "study"),
                     names(infl))
    icd <- intersect(c("cooks_d_cluster", "cooks_d", "cook_d", "cooks", "d"), names(infl))
    if (length(icl) == 0 || length(icd) == 0) {
      stop(sprintf(paste0("STOP [A3]: Cook's D neither in TF_loo.csv nor cluster-level ",
                          "in TF_influence.csv. loo header: %s; influence header: %s"),
                   paste(sort(names(loo)), collapse = ", "),
                   paste(sort(names(infl)), collapse = ", ")), call. = FALSE)
    }
    labs <- trimws(as.character(infl[[icl[1]]]))
    cds  <- suppressWarnings(as.numeric(infl[[icd[1]]]))
    keep <- !is.na(cds) & labs != ""
    cooks_map <- stats::setNames(cds[keep], labs[keep])
  }

  recs <- list()
  for (i in seq_len(nrow(loo))) {
    r <- loo[i, , drop = FALSE]
    lab <- txtv(r, label_c); est <- numv(r, "est_z", "est")
    if (is.na(lab) || lab == "" || is.na(est)) next
    ci <- ci_of(r, paste0("A3/", lab))
    cd <- if (length(cooks_c) > 0) numv(r, cooks_c[1]) else
      if (lab %in% names(cooks_map)) unname(cooks_map[[lab]]) else NA_real_
    if (is.na(cd)) stop(sprintf("STOP [A3]: no Cook's D for cluster '%s'.", lab),
                        call. = FALSE)
    recs[[length(recs) + 1]] <- list(lab = lab, est = est, lb = ci[1], ub = ci[2], cd = cd)
  }

  pin(length(recs) == 114, sprintf("A3 row count: %d != 114", length(recs)))
  ord <- order(vapply(recs, function(x) -x$cd, numeric(1)))
  recs <- recs[ord]
  pin(grepl("Drago", recs[[1]]$lab), sprintf("A3 top influence: %s", recs[[1]]$lab))
  pin(abs(recs[[1]]$cd - 1.64) <= 0.005, sprintf("A3 Drago D: %.4f", recs[[1]]$cd))
  ests <- vapply(recs, function(x) x$est, numeric(1))
  pin(abs(min(ests) - (-0.0601)) <= 5e-4 && abs(max(ests) - (-0.0409)) <= 5e-4,
      sprintf("A3 est_z range: [%.4f; %.4f]", min(ests), max(ests)))

  lines <- c(
    paste0("<!-- Table A.3 generated by scripts/build_appendix_tables.R from ",
           "output/TF_loo.csv (cluster leave-one-out refits, F4) and ",
           "output/TF_influence.csv (F5); 114 clusters; ordered by Cook's ",
           "distance, descending -->"),
    paste0("| Cluster (study) | est_z (", MINUS, "cluster) | 95% CI | Cook's D |"),
    "|---|---|---|---|")
  for (x in recs) {
    lines <- c(lines, sprintf("| %s | %s | %s | %s |", x$lab, f3(x$est),
                              fmt_ci(x$lb, x$ub), m(sprintf("%.3f", x$cd))))
  }
  lines <- c(lines, "", "*Note.* Ordered by Cook's distance.")
  paste(lines, collapse = "\n")
}

# ---------- Table A.4 : period FAT-PET-PEESE ----------

build_a4 <- function(t5) {
  cell_pet <- function(spec, subset, ctx) {
    r <- one(t5, ctx, analysis_id = "D4", spec = spec, subset = subset,
             term = "intercept")
    ci <- ci_of(r, ctx); p <- fmt_p(p_of(r))
    list(cell = sprintf("%s %s (%s)", f3(numv(r, "est_z")), fmt_ci(ci[1], ci[2]), p),
         p = p)
  }
  cell_fat <- function(spec, subset, ctx) {
    r <- one(t5, ctx, analysis_id = "D4", spec = spec, subset = subset, term = "sez")
    p <- fmt_p(p_of(r))
    list(cell = sprintf("%s (%s)", f3(numv(r, "est_z")), p), p = p)
  }
  cell_peese <- function(spec, subset, ctx) {
    ri <- one(t5, paste0(ctx, "/int"), analysis_id = "D4", spec = spec,
              subset = subset, term = "intercept")
    ci <- ci_of(ri, ctx)
    sprintf("%s %s", f3(numv(ri, "est_z")), fmt_ci(ci[1], ci[2]))
  }
  kcell <- function(subset) {
    spec <- paste0("pet_", if (subset == "defined_pre") "pre" else "post")
    r <- one(t5, paste0("A4/k/", subset), analysis_id = "D4", spec = spec,
             subset = subset, term = "intercept")
    sprintf("%s / %d", fmt_k(numv(r, "k_es")), as.integer(numv(r, "k_study")))
  }

  fat_pre  <- cell_fat("pet_pre", "defined_pre", "A4/fat_pre")
  pet_pre  <- cell_pet("pet_pre", "defined_pre", "A4/pet_pre")
  peese_pre  <- cell_peese("peese_pre", "defined_pre", "A4/peese_pre")
  fat_post <- cell_fat("pet_post", "defined_post", "A4/fat_post")
  pet_post <- cell_pet("pet_post", "defined_post", "A4/pet_post")
  peese_post <- cell_peese("peese_post", "defined_post", "A4/peese_post")

  pin(peese_pre == m("-0.058 [-0.098; -0.018]"), sprintf("A4 PEESE pre: %s", peese_pre))
  pin(peese_post == m("-0.045 [-0.061; -0.028]"), sprintf("A4 PEESE post: %s", peese_post))
  pin(pet_pre$p == ".0497" && pet_post$p == ".0098",
      sprintf("A4 PET p: %s / %s", pet_pre$p, pet_post$p))
  pin(fat_pre$p == ".162" && fat_post$p == ".0047",
      sprintf("A4 FAT p: %s / %s", fat_pre$p, fat_post$p))

  paste(c(
    paste0("<!-- Table A.4 generated by scripts/build_appendix_tables.R from ",
           "output/T5_results.csv (D4 period split: pet_pre/peese_pre/",
           "pet_post/peese_post); Fisher-z scale; the alignment rule selects ",
           "PEESE in both periods (TB-33) -->"),
    paste0("| Period | k (ES / studies) | FAT slope (p) | PET intercept ",
           "[95% CI] (p) | PEESE intercept [95% CI] | Selected |"),
    "|---|---|---|---|---|---|",
    sprintf("| Pre-Paris | %s | %s | %s | %s | PEESE |",
            kcell("defined_pre"), fat_pre$cell, pet_pre$cell, peese_pre),
    sprintf("| Post-Paris | %s | %s | %s | %s | PEESE |",
            kcell("defined_post"), fat_post$cell, pet_post$cell, peese_post)),
    collapse = "\n")
}

# ---------- main ----------

main <- function() {
  t1   <- load_csv(file.path("output", "T1_results.csv"))
  loo  <- load_csv(file.path("output", "TF_loo.csv"))
  infl <- load_csv(file.path("output", "TF_influence.csv"), required = FALSE)
  t5   <- load_csv(file.path("output", "T5_results.csv"))

  doc <- paste(c(
    paste0("<!-- appendix_tables_A2_A4.md -- generated by ",
           "scripts/build_appendix_tables.R (M7 DEC); do not edit by hand -->"),
    "", "### Table A.2", "", build_a2(t1),
    "", "### Table A.3", "", build_a3(loo, infl),
    "", "### Table A.4", "", build_a4(t5), ""), collapse = "\n")

  dir.create("output", showWarnings = FALSE)
  con <- file(OUT_PATH, open = "wb")
  writeBin(charToRaw(enc2utf8(doc)), con)
  close(con)
  cat(doc, "\n")
  message(sprintf("[build_appendix_tables] ALL PINS PASS -- written to %s", OUT_PATH))
}

main()
